### ISSUE TITLE
Clerk Authentication and Gemini AI Integration and Image Generation.

### ISSUE THREAD

**Issue by SunkaraboinaPraveenKumar** [Sahil-Gupta584/BooksMall#1]
I can integrate Clerk Authentication and take various books according to category and generate popular books with their price tags and also generate image using hugging face image generation model to generate cover page of book

**Comment by Sahil-Gupta584** [comment]
> I can integrate Clerk Authentication and take various books according to category and generate popular books with their price tags and also generate image using hugging face image generation model to generate cover page of book

Hey @SunkaraboinaPraveenKumar I am glad to know that you are interested in this project. But this project is a marketplace for actual books which users upload so we don't have to use upload any customs images or book lists. 
You can find more bugs and feature and raise pr I will definitely merge it

**Comment by SunkaraboinaPraveenKumar** [comment]
I can Use Shadcn components for better visual experience and also SignUp failed it is giving i can integrate Clerk Authentication which is free of cost and easy to use in nextjs

**Comment by Sahil-Gupta584** [comment]
Sign up is working just instead err messages it it giving fails. Appwrite gives err with message that password  is weak. Can't u use appwwrite? For clerk I think we also I have to use their react components but we have different signup form (two in one) also appwrite Is handling authentication and database both so adding new service without imp reason maybe waste. 

And using shadcn could change websites themes I wanted to keep theme for books where as shandcn is mostly for darker theme. 
Instead integrating new things we should work on improving.
