### ISSUE TITLE
Signup and login & Search bar are not working....

### ISSUE THREAD

**Issue by MakuShraddha** [Sahil-Gupta584/BooksMall#12]
The overall idea and application is good but there need to be put some efforts on display features and the functionalities.....

**Comment by Sahil-Gupta584** [comment]
> The overall idea and application is good but there need to be put some efforts on display features and the functionalities.....

i will happen with time as the project is fresh now.
if you have any idea please share by creating issue with title Feat: ...

**Comment by Trishank-K** [comment]
Hey! @Sahil-Gupta584  
I would love to work on this issue if still up for grabs

**Comment by sarwar-jahin-port** [comment]
If any way I can contribute to the issue. Please let me know.
