### ISSUE TITLE
add about us page

### ISSUE THREAD

**Issue by sanchiitvijay** [Sahil-Gupta584/BooksMall#14]
Users need to understand the essence of the website and its standout features. An "About Us" page is essential to showcase all of this information. Additionally, it should highlight the positive impact the website will have on its users.

**Comment by Sahil-Gupta584** [comment]
> Users need to understand the essence of the website and its standout features. An "About Us" page is essential to showcase all of this information. Additionally, it should highlight the positive impact the website will have on its users.

You re right about us page create good impression helps to be familiar with people. would you like to work on it?

**Comment by sanchiitvijay** [comment]
Yes. I would love to contribute. 
@Sahil-Gupta584
