### ISSUE TITLE
Search Functionality is not working 

### ISSUE THREAD

**Issue by TheSoumenMondal** [Sahil-Gupta584/BooksMall#2]
![image](https://github.com/user-attachments/assets/37d6188f-841a-4b0b-9fcd-380acca52815)
**When i am searching a book is not appearing though it is present in the webpage**

**Comment by TheSoumenMondal** [comment]
Please assign this issue to me and add the hacktoberfest label

**Comment by Sahil-Gupta584** [comment]
Yes search feature isn't yet added you can surely work on it!

**Comment by Vipul-Ydv** [comment]
hey can u assign this issue ?

**Comment by Sahil-Gupta584** [comment]
> hey can u assign this issue ?

It's been already assigned you can find new issue .
