### ISSUE TITLE
Improve Documentation : Readme

### ISSUE THREAD

**Issue by KanwalpreetSingh1823** [Sahil-Gupta584/BooksMall#24]
I want to add a detailed Readme. Please assign this issue to me under Hactoberfest.

**Comment by Sahil-Gupta584** [comment]
Sure, also try to add contributionguide.md

**Comment by KanwalpreetSingh1823** [comment]
@M-ayank2005, Yes I am Working on this issue.

**Comment by M-ayank2005** [comment]
Ok @KanwalpreetSingh1823  you can go ahead
