### ISSUE TITLE
real-time password strength analyzer

### ISSUE THREAD

**Issue by yalsik86** [Sahil-Gupta584/BooksMall#27]
Implementation of real-time password strength analysis feature for signup page.

@Sahil-Gupta584  please assign me this issue and label as hacktoberfest.

**Comment by Sahil-Gupta584** [comment]
You authenticattion system is in trouble due to issue #23 would you still able to solve this issue without solving issue #23 ?

**Comment by yalsik86** [comment]
@Sahil-Gupta584 yes, it's just a strength checking bar that I'll add and after that if you want I can look into the issue #23 Cors error as well or ask one of my colleagues to do it.
