### ISSUE TITLE
add a scroll to top button

### ISSUE THREAD

**Issue by MeetThakur** [Sahil-Gupta584/BooksMall#28]
it would be nice quality of life change

**Comment by Sahil-Gupta584** [comment]
Would like to work on it @MeetThakur ?

**Comment by MeetThakur** [comment]
@Sahil-Gupta584  yes ,I would

**Comment by Sahil-Gupta584** [comment]
Make sure no any bugs get formed and provide proper attachments as proof of work so I can merge easily
