### ISSUE TITLE
Dark and Light Mode Integration

### ISSUE THREAD

**Issue by kumartushar0605** [Sahil-Gupta584/BooksMall#3]
Dark and light mode switch for the Bookmall website to enhance user experience, especially for users who prefer different viewing modes depending on the time of day or environmental conditions.

This contribution is part of Hacktoberfest 2024.

**Comment by Sahil-Gupta584** [comment]
Sure you wanna do it?

**Comment by Sahil-Gupta584** [comment]
> Dark and light mode switch for the Bookmall website to enhance user experience, especially for users who prefer different viewing modes depending on the time of day or environmental conditions.
> 
> This contribution is part of Hacktoberfest 2024.

Sure you wanna do it?

**Comment by kumartushar0605** [comment]
@Sahil-Gupta584 yes please assign me this issue

**Comment by kumartushar0605** [comment]
@Sahil-Gupta584 please assign me i will do my best

**Comment by Sahil-Gupta584** [comment]
> @Sahil-Gupta584 please assign me i will do my best

Sure, don't forget to join attachments of you works

**Comment by kumartushar0605** [comment]
@Sahil-Gupta584  okay brother

**Comment by kumartushar0605** [comment]
@Sahil-Gupta584 bro please assign me

**Comment by Sahil-Gupta584** [comment]
Oops sure!

**Comment by kumartushar0605** [comment]
@Sahil-Gupta584  Thanks brother
