### ISSUE TITLE
Addition of Dockerfile

### ISSUE THREAD

**Issue by mayank-0407** [Sahil-Gupta584/BooksMall#42]
We can add a Dockerfile to easily use this project in an isolated container, and run the project with 1 command.

**Comment by Sahil-Gupta584** [comment]
@mayank-0407 You wanna work on it?

**Comment by mayank-0407** [comment]
@Sahil-Gupta584 Yes Please assign it to me

**Comment by Sahil-Gupta584** [comment]
@mayank-0407 I often don't know much about docker so please for beginners update documentation if needed

**Comment by mayank-0407** [comment]
@Sahil-Gupta584 ok i will update documentation accordingly!
